spring:
  application:
    name: desafio-junior-backend-simplify

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.${HIBERNATE_DIALECT}
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

server:
    port: ${SERVER_PORT}